version: '3.9'

services:

  eureka:
    build: ./discovery
    image: backend-eureka:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  config-server:
    build: ./config-server
    image: backend-config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - eureka
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - microservices-network

  actualite:
    build: ./Actualite
    image: backend-actualite-service:latest
    container_name: actualite-service
    ports:
      - "8094:8094"
    depends_on:
      - config-server
      - eureka
      - mysql
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/healthswift?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root  # Mettre le mot de passe de la base de données MySQL
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    networks:
      - microservices-network

  demande:
    build: ./Demande
    image: backend-demande-service:latest
    container_name: demande-service
    ports:
      - "8091:8091"
    depends_on:
      - config-server
      - eureka
      - mysql
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/healthswift?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root  # Mettre le mot de passe de la base de données MySQL
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    networks:
      - microservices-network

  donation:
    build: ./donation
    image: backend-donation-service:latest
    container_name: donation-service
    ports:
      - "8092:8092"
    depends_on:
      - config-server
      - eureka
      - mysql
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/healthswift?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root  # Mettre le mot de passe de la base de données MySQL
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    networks:
      - microservices-network

  evenement:
    build: ./donation
    image: backend-evenement-service:latest
    container_name: evenement-service
    ports:
      - "8093:8093"
    depends_on:
      - config-server
      - eureka
      - mysql
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/healthswift?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root  # Mettre le mot de passe de la base de données MySQL
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    networks:
      - microservices-network

  reclamation:
    build: ./reclamation
    image: backend-reclamation-service:latest
    container_name: reclamation-service
    ports:
      - "8097:8097"
    depends_on:
      - config-server
      - eureka
      - mysql
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/healthswift?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root  # Mettre le mot de passe de la base de données MySQL
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    networks:
      - microservices-network

  utilisateur:
    build: ./utilisateur
    image: backend-utilisateur-service:latest
    container_name: utilisateur-service
    ports:
      - "8096:8096"
    depends_on:
      - config-server
      - eureka
      - mysql
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/healthswift?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root  # Mettre le mot de passe de la base de données MySQL
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    networks:
      - microservices-network

  rendezvous:
    build: ./RendezVous
    image: backend-rendezvous-service:latest
    container_name: rendezvous-service
    ports:
      - "8095:8095"
    depends_on:
      - config-server
      - eureka
      - mysql
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/healthswift?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root  # Mettre le mot de passe de la base de données MySQL
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    networks:
      - microservices-network


  gateway:
    build: ./gateway
    image: backend-gateway:latest
    container_name: gateway-service
    ports:
      - "8222:8222"
    depends_on:
      - config-server
      - eureka
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:8888
    networks:
      - microservices-network

  mysql:
    image: mysql:8.0  # Utilisation de l'image officielle de MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root  # Le mot de passe pour l'utilisateur root de MySQL
      MYSQL_DATABASE: healthswift  # Créer une base de données healthswift si elle n'existe pas
    ports:
      - "3306:3306"  # Exposer le port MySQL
    volumes:
      - mysql_data:/var/lib/mysql  # Persist data between container restarts
    networks:
      - microservices-network

volumes:
  mysql_data:

networks:
  microservices-network:
    driver: bridge
