
services:

  config-server:
    build: ./config-server
    image: config:0.1
    container_name: config
    ports:
      - "8888:8888"
    networks:
      - microservices-network

  eureka:
    build: ./discovery
    image: eureka:0.1
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  gateway:
    build: ./gatew
    image: gateway:0.1
    container_name: gateway
    ports:
      - "8222:8222"
    depends_on:
      - eureka
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservices-network

  actualite:
    build: ./Actualite
    image: actualite:0.1
    container_name: actualite
    ports:
      - "8094:8094"
    depends_on:
      - config-server
      - mysql
      - eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/healthswift?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_CLOUD_CONFIG_URI=http://config:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservices-network

  demande:
    build: ./Demande
    image: demande:0.1
    container_name: demande
    ports:
      - "8091:8091"
    depends_on:
      - config-server
      - mysql
      - eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/healthswift?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_CLOUD_CONFIG_URI=http://config:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservices-network

  donation:
    build: ./donation
    image: donation:0.1
    container_name: donation
    ports:
      - "8092:8092"
    depends_on:
      - config-server
      - mysql
      - eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/healthswift?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_CLOUD_CONFIG_URI=http://config:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservices-network

  evenement:
    build: ./Evenement
    image: evenement:0.1
    container_name: evenement
    ports:
      - "8093:8093"
    depends_on:
      - config-server
      - mysql
      - eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/healthswift?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_CLOUD_CONFIG_URI=http://config:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservices-network

  reclamation:
    build: ./reclamation
    image: reclamation:0.1
    container_name: reclamation
    ports:
      - "8097:8097"
    depends_on:
      - config-server
      - mysql
      - eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/healthswift?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_CLOUD_CONFIG_URI=http://config:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservices-network

  rendez-vous:
    build: ./RendezVous
    image: rendez-vous:0.1
    container_name: rendez-vous
    ports:
      - "8095:8095"
    depends_on:
      - config-server
      - mysql
      - eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/healthswift?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_CLOUD_CONFIG_URI=http://config:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservices-network

  utilisateur:
    build: ./utilisateur
    image: utilisateur:0.1
    container_name: utilisateur
    ports:
      - "8096:8096"
    depends_on:
      - config-server
      - mysql
      - eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/healthswift?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_CLOUD_CONFIG_URI=http://config:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservices-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthswift
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - microservices-network

volumes:
  mysql_data:

networks:
  microservices-network:
    driver: bridge