spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Auth
          jwk-set-uri: http://localhost:8080/realms/Auth/protocol/openid-connect/certs
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-service
