spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: rendezVous-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true

server:
  port: 8095