spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: demande-server
          uri: lb://demande-server
          predicates:
            - Path=/api/demande/**
        - id: donation-server
          uri: lb://donation-server
          predicates:
            - Path=/api/don/**
        - id: evenementactualite-server
          uri: lb://evenementactualite-server
          predicates:
            - Path=/api/evenementactualite/**
        - id: notification-server
          uri: lb://notification-server
          predicates:
            - Path=/api/notification/**
        - id: rendezVous-server
          uri: lb://rendezVous-server
          predicates:
            - Path=/api/rendezVous/**
        - id: utilisateur-server
          uri: lb://utilisateur-server
          predicates:
            - Path=/api/user/**

        - id: actualite-server
          uri: lb://actualite-server
          predicates:
            - Path=/api/Actualite/**

        - id: material-service
          uri: lb://material-service
          predicates:
            - Path=/api/materials/**







eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8222
# Keycloak Configuration
keycloak:
  enabled: true
  auth-server-url: http://localhost:8180/auth
  realm: Auth
  resource: praktika-Auth
  public-client: true
  principal-attribute: preferred_username
####################
