spring:
  config:
     import: optional:configserver:http://localhost:8888
  application:
    name: demande-server
  mail:
    host: smtp.gmail.com
    port: 587
    username: stakwa336@gmail.com
    password: iabspyodwscbunll
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true

server:
  port: 8091


